package avroGeneratedClasses; /**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */

import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.SchemaStore;
import org.apache.avro.specific.SpecificData;

@org.apache.avro.specific.AvroGenerated
public class Inventory extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -6751035409876357580L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"Inventory\",\"fields\":[{\"name\":\"inventoryList\",\"type\":{\"type\":\"record\",\"name\":\"InventoryList\",\"fields\":[{\"name\":\"header\",\"type\":{\"type\":\"record\",\"name\":\"Header\",\"fields\":[{\"name\":\"defaultInstock\",\"type\":\"boolean\"},{\"name\":\"listId\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"onOrder\",\"type\":\"boolean\"},{\"name\":\"useBundleInventoryOnly\",\"type\":\"boolean\"}]}},{\"name\":\"records\",\"type\":{\"type\":\"array\",\"items\":{\"type\":\"record\",\"name\":\"Record\",\"fields\":[{\"name\":\"allocation\",\"type\":\"int\"},{\"name\":\"allocationTimestamp\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"perpetual\",\"type\":\"boolean\"},{\"name\":\"preorderBackorderHandling\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"productId\",\"type\":\"int\"}]}}}]}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<Inventory> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<Inventory> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<Inventory> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<Inventory> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<Inventory> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this Inventory to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a Inventory from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a Inventory instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static Inventory fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private InventoryList inventoryList;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public Inventory() {}

  /**
   * All-args constructor.
   * @param inventoryList The new value for inventoryList
   */
  public Inventory(InventoryList inventoryList) {
    this.inventoryList = inventoryList;
  }

  @Override
  public SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public Object get(int field$) {
    switch (field$) {
    case 0: return inventoryList;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, Object value$) {
    switch (field$) {
    case 0: inventoryList = (InventoryList)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'inventoryList' field.
   * @return The value of the 'inventoryList' field.
   */
  public InventoryList getInventoryList() {
    return inventoryList;
  }


  /**
   * Sets the value of the 'inventoryList' field.
   * @param value the value to set.
   */
  public void setInventoryList(InventoryList value) {
    this.inventoryList = value;
  }

  /**
   * Creates a new Inventory RecordBuilder.
   * @return A new Inventory RecordBuilder
   */
  public static Builder newBuilder() {
    return new Builder();
  }

  /**
   * Creates a new Inventory RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new Inventory RecordBuilder
   */
  public static Builder newBuilder(Builder other) {
    if (other == null) {
      return new Builder();
    } else {
      return new Builder(other);
    }
  }

  /**
   * Creates a new Inventory RecordBuilder by copying an existing Inventory instance.
   * @param other The existing instance to copy.
   * @return A new Inventory RecordBuilder
   */
  public static Builder newBuilder(Inventory other) {
    if (other == null) {
      return new Builder();
    } else {
      return new Builder(other);
    }
  }

  /**
   * RecordBuilder for Inventory instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<Inventory>
    implements org.apache.avro.data.RecordBuilder<Inventory> {

    private InventoryList inventoryList;
    private InventoryList.Builder inventoryListBuilder;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.inventoryList)) {
        this.inventoryList = data().deepCopy(fields()[0].schema(), other.inventoryList);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (other.hasInventoryListBuilder()) {
        this.inventoryListBuilder = InventoryList.newBuilder(other.getInventoryListBuilder());
      }
    }

    /**
     * Creates a Builder by copying an existing Inventory instance
     * @param other The existing instance to copy.
     */
    private Builder(Inventory other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.inventoryList)) {
        this.inventoryList = data().deepCopy(fields()[0].schema(), other.inventoryList);
        fieldSetFlags()[0] = true;
      }
      this.inventoryListBuilder = null;
    }

    /**
      * Gets the value of the 'inventoryList' field.
      * @return The value.
      */
    public InventoryList getInventoryList() {
      return inventoryList;
    }


    /**
      * Sets the value of the 'inventoryList' field.
      * @param value The value of 'inventoryList'.
      * @return This builder.
      */
    public Builder setInventoryList(InventoryList value) {
      validate(fields()[0], value);
      this.inventoryListBuilder = null;
      this.inventoryList = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'inventoryList' field has been set.
      * @return True if the 'inventoryList' field has been set, false otherwise.
      */
    public boolean hasInventoryList() {
      return fieldSetFlags()[0];
    }

    /**
     * Gets the Builder instance for the 'inventoryList' field and creates one if it doesn't exist yet.
     * @return This builder.
     */
    public InventoryList.Builder getInventoryListBuilder() {
      if (inventoryListBuilder == null) {
        if (hasInventoryList()) {
          setInventoryListBuilder(InventoryList.newBuilder(inventoryList));
        } else {
          setInventoryListBuilder(InventoryList.newBuilder());
        }
      }
      return inventoryListBuilder;
    }

    /**
     * Sets the Builder instance for the 'inventoryList' field
     * @param value The builder instance that must be set.
     * @return This builder.
     */

    public Builder setInventoryListBuilder(InventoryList.Builder value) {
      clearInventoryList();
      inventoryListBuilder = value;
      return this;
    }

    /**
     * Checks whether the 'inventoryList' field has an active Builder instance
     * @return True if the 'inventoryList' field has an active Builder instance
     */
    public boolean hasInventoryListBuilder() {
      return inventoryListBuilder != null;
    }

    /**
      * Clears the value of the 'inventoryList' field.
      * @return This builder.
      */
    public Builder clearInventoryList() {
      inventoryList = null;
      inventoryListBuilder = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public Inventory build() {
      try {
        Inventory record = new Inventory();
        if (inventoryListBuilder != null) {
          try {
            record.inventoryList = this.inventoryListBuilder.build();
          } catch (org.apache.avro.AvroMissingFieldException e) {
            e.addParentField(record.getSchema().getField("inventoryList"));
            throw e;
          }
        } else {
          record.inventoryList = fieldSetFlags()[0] ? this.inventoryList : (InventoryList) defaultValue(fields()[0]);
        }
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<Inventory>
    WRITER$ = (org.apache.avro.io.DatumWriter<Inventory>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<Inventory>
    READER$ = (org.apache.avro.io.DatumReader<Inventory>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    this.inventoryList.customEncode(out);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      if (this.inventoryList == null) {
        this.inventoryList = new InventoryList();
      }
      this.inventoryList.customDecode(in);

    } else {
      for (int i = 0; i < 1; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          if (this.inventoryList == null) {
            this.inventoryList = new InventoryList();
          }
          this.inventoryList.customDecode(in);
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










